### ISSUE TITLE
Pre-flight checks with parsed return data

### ISSUE THREAD

**Issue by spengrah** [Hats-Protocol/sdk-v1-core#2]
Many protocol functions require one or more conditions to be true before they can be successfully executed, returning custom errors when those conditions are not met. Predicting, parsing, and displaying those errors to users would enhance app UX. 

I think there are two main categories of approaches here:

1. Run pre-flight staticcall version of a function call, parse the returndata, and then describe / elaborate on any errors that are thrown. This ensures correctness, but not completeness: for functions which have multiple prerequisites, if an early prereq fails there won't be errors thrown for any subsequent prereq even if they would fail too.

3. Proactively check all prerequisites for the function
   - this could be done with RPC calls (see #1) for maximum confidence in liveness of results, or 
   - with subgraph queries

**Comment by gershido** [comment]
Thanks for the feedback!
The SDK includes pre-flight checks for almost all possible expected reverts. I took approach number (2). There's a documentation on every write function about the different errors. Here's an example:
https://github.com/Hats-Protocol/sdk-v1-core/blob/main/src/client/index.ts#L752

On the errors list, the only error that results from a transaction is `TransactionRevertedError`. All the others are checked by calling different Hats functions like `isAdminOfHat` and so on.
The only one function that its revert condition is not covered, is `renounceHat`, because there's no public/external function to check the static balance of a wearer

**Comment by spengrah** [comment]
Oh, awesome! Serves me right for not looking at the code in-depth 😉

I'll take a closer look soon.
